<!DOCTYPE html>
<html>
<head>
    <title>Certificate - {{ $doc->name ?? 'Document' }}</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; margin: 0; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #0f172a; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; margin-bottom: 10px; text-transform: uppercase; }
        .subtitle { font-size: 14px; color: #666; }
        .section { margin-bottom: 20px; }
        .section-title { font-size: 16px; font-weight: bold; color: #0f172a; border-bottom: 1px solid #ccc; padding-bottom: 5px; margin-bottom: 15px; }
        .field { margin-bottom: 10px; }
        .field-label { font-weight: bold; width: 170px; display: inline-block; text-transform: uppercase; font-size: 12px; color: #666;}
        .field-value { display: inline-block; font-size: 14px; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Extracted Certificate Data Report</div>
        <div class="subtitle">Republic of the Philippines<br>Municipality of Naic</div>
    </div>

    <div class="section">
        <div class="section-title">Record Details</div>
        <div class="field">
            <span class="field-label">Document Type:</span>
            <span class="field-value" style="text-transform: capitalize;">{{ $doc->detected_type ?? $doc->type ?? 'N/A' }}</span>
        </div>
        <div class="field">
            <span class="field-label">System Record ID:</span>
            <span class="field-value">{{ $doc->id ?? 'N/A' }}</span>
        </div>
        <div class="field">
            <span class="field-label">Encoded By:</span>
            <span class="field-value">{{ $doc->encoded_by ?? 'System' }}</span>
        </div>
        <div class="field">
            <span class="field-label">Date Processed:</span>
            <span class="field-value">{{ date('F d, Y') }}</span>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Extracted Information</div>
        @if(isset($fields) && !empty($fields))
            @foreach($fields as $key => $value)
                <div class="field">
                    <span class="field-label">{{ ucwords(str_replace('_', ' ', $key)) }}:</span>
                    <span class="field-value">{{ $value ?: 'N/A' }}</span>
                </div>
            @endforeach
        @else
            <p>No extracted fields available.</p>
        @endif
    </div>

    <div class="footer">
        Generated by CiviCORE Automated OCR System <br>
        Document Hash: {{ md5(json_encode($fields ?? [])) }}
    </div>
</body>
</html>
